spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_card_manage_system
    username: root
    password: 666666
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      password: 666666
      cluster:
        nodes: 192.168.43.131:6381,192.168.43.131:6382,192.168.43.131:6383,192.168.43.131:6384,192.168.43.131:6385,192.168.43.131:6386
        max-redirects: 5
      lettuce:
        pool:
          # 连接池最大连接数默认值为8
          max-active: 1000
          # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
          max-wait: -1
          # 连接池中最大空闲连接数默认值为8
          max-idle: 10
          # 连接池中的最小空闲连接数，默认值为0
          min-idle: 10

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true